### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by Merith-TK** [darenliang/dscli#2]
Cant do anything, not authorized depsite Account/Bot being admin

**Comment by darenliang** [comment]
For bots, you'll need to add the "Bot " prefix.

Example: Bot xxxxx.yyyyy.zzzzz
Not like this: xxxxx.yyyyy.zzzzz

It might be confusing, so I'll add a bot flag for the config command in the next release.

**Comment by darenliang** [comment]
Update: I've added a bot flag in release 1.11.1.

Example:
```
dscli config -t=<YOUR-DISCORD-BOT-TOKEN> -i=<YOUR-SERVER-ID> -b
```

The bot prefix way still works:
```
dscli config -t="Bot <YOUR-DISCORD-BOT-TOKEN>" -i=<YOUR-SERVER-ID>
```

Please let me know if this works on your end. Thanks.

**Comment by Merith-TK** [comment]
Yep putting `Bot <token>` worked!

**Comment by Merith-TK** [comment]
I wonder... do you think it would be possible to make a background runner for this to constantly keep it incheck? like pinging the server for a file list to compare to the local filelist every five... ten minutes or so?

**Comment by darenliang** [comment]
That's great! The Discord API requires "Bot " to be added in front of a bot token so that creates quite a bit of confusion.

> I wonder... do you think it would be possible to make a background runner for this to constantly keep it incheck? like pinging the server for a file list to compare to the local filelist every five... ten minutes or so?

Not quite sure what you mean. Are you referring to syncing files automatically?

**Comment by Merith-TK** [comment]
Yeah, syncing files automatically! However that would require a small timestamp for *last edit* to be implemented

**Comment by darenliang** [comment]
I think this would need to be implemented as an external tool.

Fortunately, you can get the timestamps with `dscli ls -l`. Each line is in the format `<filesize> <unix timestamp> <filename>`.

I don't really think it is possible to edit files without major changes, so the best that can be done currently is comparing timestamps, deleting the old file and uploading the new file.

**Comment by Merith-TK** [comment]
> deleting the old file and uploading the new file.

Or deleting the old file, and downloading the new one

**Comment by darenliang** [comment]
Oh I see, the other way around.

It is a lot more doable I think if that is the case.

**Comment by Merith-TK** [comment]
ViceVersa would be nice, but if it is setup as a one way sync that would be cool!

**Comment by darenliang** [comment]
That sounds cool!

However, I think dscli should stay the way it is, with additional functionality provided by external tools. Here is an example of a basic GUI frontend to make it easier to upload and download files (https://github.com/darenliang/dsgui).

**Comment by Merith-TK** [comment]
oh neat! Did not know that even existed!
